const $ = id => document.getElementById(id);
const inputIds = ['income','otherIncome','essential','nonEssential','savings','existingDebt','goalContribution','price','downPayment','rate','tenure','alternative','delay','waitSaving','waitChange','growth','growthYears','stressScenario','shock','customIncome','customExpenseRise','customExpense'];
const presets={income10:{incomeDrop:10},income25:{incomeDrop:25},expense15:{expenseRise:15},expense25:{unexpected:25000},expense50:{unexpected:50000},combined:{incomeDrop:20,unexpected:25000}};
const num=id=>Number($(id).value)||0; const fmt=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n); const coverage=n=>n===null?'Not calculable':`${n.toFixed(1)} months`;
function read(){return {income:num('income')+num('otherIncome'),essential:num('essential'),nonEssential:num('nonEssential'),savings:num('savings'),debt:num('existingDebt'),goal:num('goalContribution'),price:num('price'),down:num('downPayment'),rate:num('rate'),tenure:Math.round(num('tenure')),alternative:num('alternative'),delay:Math.round(num('delay')),waitSaving:num('waitSaving'),waitChange:num('waitChange'),growth:num('growth'),growthYears:num('growthYears')}}
function calc(){const v=read(),error=[];if(v.price<=0)error.push('Purchase price must be greater than zero.');if(v.down>v.price||v.down<0)error.push('Down payment must be between Rs. 0 and the purchase price.');if(v.rate<0)error.push('Interest rate cannot be negative.');if(v.tenure<1)error.push('EMI tenure must be a positive integer.');if(v.alternative<=0)error.push('Lower-cost alternative price must be greater than zero.');$('validation').textContent=error.join(' ');if(error.length)return;
const surplus=v.income-v.essential-v.nonEssential-v.debt, cov=s=>v.essential===0?null:s/v.essential, fv=x=>x*Math.pow(1+v.growth/100,v.growthYears), delay=x=>v.goal>0?x/v.goal:null;
const principal=v.price-v.down, monthly=v.rate===0?principal/v.tenure:principal*((v.rate/1200)*Math.pow(1+v.rate/1200,v.tenure))/(Math.pow(1+v.rate/1200,v.tenure)-1), repayment=monthly*v.tenure, waitPrice=v.price*(1+v.waitChange/100);
const scenarios=[{name:'Cash now',payment:v.price,emi:0,cost:v.price,interest:0,savings:v.savings-v.price,surplus,note:'Pays the full price today; no financing interest.'},{name:'EMI',payment:v.down,emi:monthly,cost:v.down+repayment,interest:repayment-principal,savings:v.savings-v.down,surplus:surplus-monthly,note:'EMI remains a monthly obligation for the selected tenure.'},{name:'Wait & save',payment:0,emi:0,cost:waitPrice,interest:0,savings:v.savings+v.waitSaving*v.delay-waitPrice,surplus,note:`Price after waiting uses your ${v.waitChange.toFixed(1)}% price-change assumption.`},{name:'Lower-cost alternative',payment:v.alternative,emi:0,cost:v.alternative,interest:0,savings:v.savings-v.alternative,surplus,note:'Lower monetary cost does not assess quality or suitability.'}].map(x=>({...x,coverage:cov(x.savings),goalDelay:delay(x.payment||x.cost),future:fv(x.payment||x.cost)}));
render(v,surplus,cov(v.savings),scenarios);}
function card(label,value,negative=false){return `<div class="metric"><div class="label">${label}</div><div class="value ${negative?'negative':''}">${value}</div></div>`}
function render(v,surplus,baseCoverage,s){$('baselineMetrics').innerHTML=card('Total monthly income (calculation)',fmt(v.income))+card('Monthly surplus / deficit (calculation)',fmt(surplus),surplus<0)+card('Emergency coverage (calculation)',coverage(baseCoverage))+card('Available savings (input)',fmt(v.savings));$('scenarioCards').innerHTML=s.map(x=>`<article class="scenario-card"><div class="label">${x.name}</div><h3>${fmt(x.cost)} total cost</h3><div class="value ${x.surplus<0?'negative':''}">${fmt(x.surplus)} / month</div><p>${x.note}</p><p><strong>Emergency coverage:</strong> ${coverage(x.coverage)}</p><p><strong>PROJECTION:</strong> ${fmt(x.future)} hypothetical future value under ${v.growth}% for ${v.growthYears} years.</p></article>`).join('');$('comparisonBody').innerHTML=s.map(x=>`<tr><td><strong>${x.name}</strong></td><td>${fmt(x.payment)}</td><td>${fmt(x.emi)}</td><td>${fmt(x.cost)}</td><td>${fmt(x.interest)}</td><td>${fmt(x.savings)}</td><td class="${x.surplus<0?'negative':''}">${fmt(x.surplus)}</td><td>${coverage(x.coverage)}</td></tr>`).join('');const low=s.reduce((a,b)=>a.cost<b.cost?a:b), liquid=s.reduce((a,b)=>a.savings>b.savings?a:b), debt=s.reduce((a,b)=>a.emi<b.emi?a:b);$('tradeoffs').innerHTML=`<strong>Factual trade-offs under current inputs</strong><ul><li>Lowest total cost: ${low.name} (${fmt(low.cost)})</li><li>Highest immediate liquidity: ${liquid.name} (${fmt(liquid.savings)})</li><li>Lowest new monthly debt: ${debt.name} (${fmt(debt.emi)}/month)</li></ul>`;renderCharts(s);renderStress(v,s);}
function chart(title,key,kind='blue'){const s=window.scenarios,max=Math.max(...s.map(x=>Math.abs(x[key])),1);return `<div class="bar-chart"><h4>${title}</h4>${s.map(x=>`<div class="bar-row"><span>${x.name}</span><div class="bar-track"><div class="bar ${kind}" style="width:${Math.abs(x[key])/max*100}%"></div></div><strong>${key==='coverage'?coverage(x[key]):fmt(x[key])}</strong></div>`).join('')}</div>`}function renderCharts(s){window.scenarios=s;$('charts').innerHTML=chart('Total cost','cost')+chart('Savings remaining','savings','good')+chart('Monthly cash flow','surplus','warn')}
function renderStress(v,s){const scenario=s.find(x=>x.name===$('stressScenario').value)||s[0],custom=$('shock').value==='custom'?{incomeDrop:num('customIncome'),expenseRise:num('customExpenseRise'),unexpected:num('customExpense')}:presets[$('shock').value]||{};const income=v.income*(1-(custom.incomeDrop||0)/100),essential=v.essential*(1+(custom.expenseRise||0)/100),savings=scenario.savings-(custom.unexpected||0),surplus=income-essential-v.nonEssential-v.debt-scenario.emi,cov=essential===0?null:savings/essential;const stage=(name,a,b,c)=>`<div class="stress-card"><div class="label">${name}</div><div class="value ${b<0?'negative':''}">${fmt(a)}</div><p>Monthly surplus / deficit: <strong class="${b<0?'negative':''}">${fmt(b)}</strong></p><p>Emergency coverage: <strong>${coverage(c)}</strong></p></div>`;$('stressOutput').innerHTML=stage('Before decision',v.savings,v.income-v.essential-v.nonEssential-v.debt,v.essential===0?null:v.savings/v.essential)+stage('After decision',scenario.savings,scenario.surplus,scenario.coverage)+stage('After stress scenario',savings,surplus,cov)}
inputIds.forEach(id=>$(id).addEventListener('input',calc));$('demo').addEventListener('click',()=>{const demo={income:50000,otherIncome:0,essential:25000,nonEssential:8000,savings:150000,existingDebt:2000,goalContribution:5000,description:'Laptop',price:60000,downPayment:10000,rate:12,tenure:12,alternative:45000,delay:6,waitSaving:8000,waitChange:0,growth:6,growthYears:3};Object.entries(demo).forEach(([k,v])=>$(k).value=v);calc();location.hash='comparison'});calc();
